export const RECIPE_LIST_REQUEST = "RECIPE_LIST_REQUEST";
export const RECIPE_LIST_SUCCESS = "RECIPE_LIST_SUCCESS";
export const RECIPE_LIST_FAIL = "RECIPE_LIST_FAIL";
export const RECIPE_LIST_UPDATE_REQUEST = "RECIPE_LIST_UPDATE_REQUEST";

export const RECIPE_DETAILS_REQUEST = "RECIPE_DETAILS_REQUEST";
export const RECIPE_DETAILS_SUCCESS = "RECIPE_DETAILS_SUCCESS";
export const RECIPE_DETAILS_FAIL = "RECIPE_DETAILS_FAIL";

export const RECIPE_CREATE_REQUEST = "RECIPE_CREATE_REQUEST";
export const RECIPE_CREATE_SUCCESS = "RECIPE_CREATE_SUCCESS";
export const RECIPE_CREATE_FAIL = "RECIPE_CREATE_FAIL";
export const RECIPE_CREATE_RESET = "RECIPE_CREATE_RESET";

export const RECIPE_SET_RATING_REQUEST = "RECIPE_SET_RATING_REQUEST";
export const RECIPE_SET_RATING_SUCCESS = "RECIPE_SET_RATING_SUCCESS";
export const RECIPE_SET_RATING_FAIL = "RECIPE_SET_RATING_FAIL";
export const RECIPE_SET_RATING_RESET = "RECIPE_SET_RATING_RESET";

export const RECIPE_ADD_FOLLOWER_REQUEST = "RECIPE_ADD_FOLLOWER_REQUEST";
export const RECIPE_ADD_FOLLOWER_SUCCESS = "RECIPE_ADD_FOLLOWER_SUCCESS";
export const RECIPE_ADD_FOLLOWER_FAIL = "RECIPE_ADD_FOLLOWER_FAIL";

export const RECIPE_REMOVE_FOLLOWER_REQUEST = "RECIPE_REMOVE_FOLLOWER_REQUEST";
export const RECIPE_REMOVE_FOLLOWER_SUCCESS = "RECIPE_REMOVE_FOLLOWER_SUCCESS";
export const RECIPE_REMOVE_FOLLOWER_FAIL = "RECIPE_REMOVE_FOLLOWER_FAIL";

export const RECIPE_ADD_COMMENT_REQUEST = "RECIPE_ADD_COMMENT_REQUEST";
export const RECIPE_ADD_COMMENT_SUCCESS = "RECIPE_ADD_COMMENT_SUCCESS";
export const RECIPE_ADD_COMMENT_FAIL = "RECIPE_ADD_COMMENT_FAIL";

export const RECIPE_USERLIST_REQUEST = "RECIPE_USERLIST_REQUEST";
export const RECIPE_USERLIST_SUCCESS = "RECIPE_USERLIST_SUCCESS";
export const RECIPE_USERLIST_FAIL = "RECIPE_USERLIST_FAIL";
export const RECIPE_USERLIST_UPDATE_REQUEST = "RECIPE_USERLIST_UPDATE_REQUEST";

export const RECIPE_FAVORITES_LIST_REQUEST = "RECIPE_FAVORITES_LIST_REQUEST";
export const RECIPE_FAVORITES_LIST_SUCCESS = "RECIPE_FAVORITES_LIST_SUCCESS";
export const RECIPE_FAVORITES_LIST_FAIL = "RECIPE_FAVORITES_LIST_FAIL";
export const RECIPE_FAVORITES_LIST_UPDATE_REQUEST =
  "RECIPE_FAVORITES_LIST_UPDATE_REQUEST";
