export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";
export const USER_REGISTER_RESET = "USER_REGISTER_RESET";

export const USER_DETAILS_REQUEST = "USER_DETAILS_REQUEST";
export const USER_DETAILS_SUCCESS = "USER_DETAILS_SUCCESS";
export const USER_DETAILS_FAIL = "USER_DETAILS_FAIL";
export const USER_DETAILS_RESET = "USER_DETAILS_RESET";

export const USER_PROFILE_REQUEST = "USER_PROFILE_REQUEST";
export const USER_PROFILE_SUCCESS = "USER_PROFILE_SUCCESS";
export const USER_PROFILE_FAIL = "USER_PROFILE_FAIL";
export const USER_PROFILE_RESET = "USER_PROFILE_RESET";

export const USER_ADD_FOLLOWER_REQUEST = "USER_ADD_FOLLOWER_REQUEST";
export const USER_ADD_FOLLOWER_SUCCESS = "USER_ADD_FOLLOWER_SUCCESS";
export const USER_ADD_FOLLOWER_FAIL = "USER_ADD_FOLLOWER_FAIL";

export const USER_REMOVE_FOLLOWER_REQUEST = "USER_REMOVE_FOLLOWER_REQUEST";
export const USER_REMOVE_FOLLOWER_SUCCESS = "USER_REMOVE_FOLLOWER_SUCCESS";
export const USER_REMOVE_FOLLOWER_FAIL = "USER_REMOVE_FOLLOWER_FAIL";

export const USER_FOLLOWING_REQUEST = "USER_FOLLOWING_REQUEST";
export const USER_FOLLOWING_SUCCESS = "USER_FOLLOWING_SUCCESS";
export const USER_FOLLOWING_FAIL = "USER_FOLLOWING_FAIL";
export const USER_FOLLOWING_UPDATE_REQUEST = "USER_FOLLOWING_UPDATE_REQUEST";
